### ISSUE TITLE
.pptx cannot be downloaded as report

### ISSUE THREAD

**Issue by agalperina** [abbvie-external/OmicNavigatorWebApp#60]
V: 1.3.3 package: 1.5.2

.pptx are successfully added to study object as report; however, on ON the button to download report is greyed out and the .pptx cannot be downloaded.

**Comment by bengalengel** [comment]
I can confirm this is no longer working with the current version of the software. It was working with version 1.2.1 and package 1.5.1. We will investigate further. I see no reports folder following installation.

**Comment by jdblischak** [comment]
@agalperina Thanks for the bug report! I'm not sure what's going on. Below is a minimal, reproducible example. Could you please run it and let me know the results?

```R
# Create pptx file
library("officer")
pptx <- read_pptx()
pptx <- add_slide(pptx, layout = "Title and Content", master = "Office Theme")
pptx <- ph_with(pptx, value = "My report", location = ph_location_type(type = "title"))
report <- tempfile(fileext = ".pptx")
print(pptx, target = report)

# Add report to OmicNavigator study
library("OmicNavigator")
study <- OmicNavigator:::testStudyMinimal()
study[["name"]] <- "pptxReport"
study <- addReports(study, reports = list(default = report))
installStudy(study)
startApp()
```

I was not able to reproduce the bug. I tested with R 4.0.5 on Windows 10 with the following configurations:

1. pkg 1.4.3, app 1.1.9 (latest CRAN release)
2. pkg 1.5.2, app 1.3.1 (close to your versions, though I used the pinned version of the app)
3. pkg 1.6.3.2, app 1.3.4 (development version on GitHub)

Some ideas:

1. Does your pptx file name have any spaces? Does it contain any non-standard characters? Is the file located on a Windows drive that is different from where the package is installed?
2. Can you try running `installApp(overwrite = TRUE)` so that the app version is the exact pinned version for pkg 1.5.2? App version 1.3.3 is meant to be used with pkg version 1.6.2. You might also need to do a hard refresh of your browser to get the package versions to report correctly in the app

**Comment by agalperina** [comment]
I was able to upload a .pptx using the reproducible code; however, the .pptx for the study is still not uploading. I changed the file name to remove spaces and make it shorter, ran installApp(overwrite=TRUE) and did a hard refresh on my browser. I am running 1.6.3 of ON.

**Comment by jdblischak** [comment]
We figured out the issue. There was a typo in the modelID used when registering the report file with `addReports()`. Thus it wasn't available when the modelID was selected in the app.

Conclusion: There are no known restrictions on the types of files that can be included as reports.
